export const OPENCLAW_STORAGE_KEY = "openclaw-state-v1";

const now = new Date("2026-03-19T14:30:00+05:30");

const isoMinutesAgo = (minutes) => new Date(now.getTime() - minutes * 60_000).toISOString();
const isoHoursAgo = (hours) => new Date(now.getTime() - hours * 3_600_000).toISOString();
const isoDaysAgo = (days) => new Date(now.getTime() - days * 86_400_000).toISOString();
const isoDaysFromNow = (days) => new Date(now.getTime() + days * 86_400_000).toISOString();

export const skillCatalog = [
  { id: "dsa-bulk-importer", category: "DSA Outreach", name: "dsa-bulk-importer", summary: "Import CSV/Excel of DSA contacts, deduplicate, tag, segment", status: "Ready" },
  { id: "dsa-cold-messenger", category: "DSA Outreach", name: "dsa-cold-messenger", summary: "Execute mass outreach campaigns with message rotation, staggered timing, anti-ban controls", status: "Ready" },
  { id: "dsa-followup-engine", category: "DSA Outreach", name: "dsa-followup-engine", summary: "Multi-stage follow-up sequences for non-responding DSAs", status: "Ready" },
  { id: "dsa-instant-responder", category: "DSA Outreach", name: "dsa-instant-responder", summary: "Detect incoming DSA reply, parse intent, auto-respond within 30 seconds", status: "Ready" },
  { id: "dsa-relationship-nurture", category: "DSA Outreach", name: "dsa-relationship-nurture", summary: "Weekly check-ins, festive wishes, product updates, commission updates", status: "Ready" },
  { id: "dsa-performance-tracker", category: "DSA Outreach", name: "dsa-performance-tracker", summary: "Track per-DSA metrics: leads referred, converted, commission earned, engagement level", status: "Ready" },
  { id: "lead-extractor", category: "Lead Management", name: "lead-extractor", summary: "Parse borrower details from unstructured DSA messages", status: "Ready" },
  { id: "lead-pipeline-manager", category: "Lead Management", name: "lead-pipeline-manager", summary: "Move leads through stages, detect stale leads, trigger follow-ups", status: "Ready" },
  { id: "lead-document-chaser", category: "Lead Management", name: "lead-document-chaser", summary: "Auto-remind leads about missing documents with escalating urgency", status: "Ready" },
  { id: "lead-instant-responder", category: "Lead Management", name: "lead-instant-responder", summary: "Answer common lead queries instantly", status: "Ready" },
  { id: "lead-status-updater", category: "Lead Management", name: "lead-status-updater", summary: "Notify referring DSA at every stage change", status: "Ready" },
  { id: "collection-sequence-runner", category: "Collections", name: "collection-sequence-runner", summary: "Execute pre-due through NPA-flag collection message sequences", status: "Ready" },
  { id: "ptp-tracker", category: "Collections", name: "ptp-tracker", summary: "Log Promise-to-Pay, auto-follow-up on PTP dates, track fulfillment rate", status: "Ready" },
  { id: "payment-logger", category: "Collections", name: "payment-logger", summary: "Record payments, handle partial payments, generate receipts", status: "Ready" },
  { id: "cheque-bounce-handler", category: "Collections", name: "cheque-bounce-handler", summary: "Auto-trigger follow-up on bounced cheques", status: "Ready" },
  { id: "npa-flagger", category: "Collections", name: "npa-flagger", summary: "Auto-detect 90+ DPD accounts, generate NPA reports", status: "Ready" },
  { id: "legal-notice-drafter", category: "Collections", name: "legal-notice-drafter", summary: "Generate legal notice drafts for 30+ day overdue accounts", status: "Ready" },
  { id: "mediator-daily-tasker", category: "Mediator Management", name: "mediator-daily-tasker", summary: "Generate and send daily task lists to mediators via WhatsApp every morning", status: "Ready" },
  { id: "mediator-visit-parser", category: "Mediator Management", name: "mediator-visit-parser", summary: "Parse visit reports, create PTP entries, update borrower profiles", status: "Ready" },
  { id: "mediator-performance-scorer", category: "Mediator Management", name: "mediator-performance-scorer", summary: "Calculate and display per-mediator scorecards and leaderboards", status: "Ready" },
  { id: "commission-calculator", category: "Mediator Management", name: "commission-calculator", summary: "Auto-calculate commissions, generate monthly statements, track payouts", status: "Ready" },
  { id: "morning-briefing", category: "General Operations", name: "morning-briefing", summary: "Generate comprehensive daily briefing across all modules, send via WhatsApp at 7 AM", status: "Ready" },
  { id: "smart-scheduler", category: "General Operations", name: "smart-scheduler", summary: "Learn optimal messaging times per contact based on response history", status: "Ready" },
  { id: "multi-language-messenger", category: "General Operations", name: "multi-language-messenger", summary: "Draft messages in English, Hindi, Tamil, Telugu, Kannada", status: "Ready" },
];

export const templateLibrary = {
  outreach: [
    "Hi {{name}}, I'm Arjun from OpenClaw Finance. We process Personal, Business, Home and Gold Loans quickly. If you have any active cases, please share. Attractive DSA commissions available.",
    "Hello {{name}}, we are onboarding active DSA partners in {{city}} for fast PL, BL, HL and GL processing. If you'd like to work together, I can share the commission structure.",
    "Hi {{name}}, we are disbursing faster this month for salaried and self-employed profiles. If you have referral cases in {{city}}, send them over and we will move fast.",
  ],
  followup: [
    "Hi {{name}}, following up on my earlier note. Any active loan cases this week? We are offering strong support and quick processing.",
    "Hello {{name}}, checking whether you are active in referrals right now. Happy to support PL, BL, HL and GL with reliable TAT.",
    "Hi {{name}}, one of our Chennai DSAs earned ₹45,000 in commission last month. If you have fresh cases, send them and we will help convert fast.",
    "Hi {{name}}, this is my last follow-up for now. If you have loan cases later, my number stays open. Wishing you a strong month ahead.",
  ],
  documents: [
    "Hi {{name}}, we need your Aadhaar, PAN and latest salary proof to move your {{loanType}} application forward. Please share when possible.",
    "Hi {{name}}, your file is almost ready. Pending documents: {{missingDocuments}}. Once shared, we can push the case for review.",
  ],
  collections: [
    "Hi {{name}}, friendly reminder that your EMI of ₹{{emi}} is due on {{dueDate}}. Please ensure payment is arranged.",
    "Hi {{name}}, your account is {{daysPastDue}} days overdue. Outstanding amount: ₹{{outstanding}}. Please clear this to avoid escalation.",
  ],
  mediator: [
    "Good morning {{name}}. Here are your tasks for today: {{tasks}}. Please update me after each visit.",
    "Hi {{name}}, you had {{pendingTasks}} pending visits today. Share your updates before close of business.",
  ],
};

export const demoCsv = `Name,Phone,City/Area,Source,Loan Types They Handle
Selvam,9876501111,Chennai,WhatsApp export,Home Loan|Personal Loan
Meena,9876502222,Coimbatore,Referral,Gold Loan|Business Loan
Irfan,9876503333,Hyderabad,Telegram list,Personal Loan|Business Loan`;

export const createInitialOpenClawState = () => ({
  generatedAt: now.toISOString(),
  dsaContacts: [
    {
      id: "dsa-001",
      name: "Rajesh Kumar",
      phone: "9876543210",
      city: "Chennai",
      source: "WhatsApp export",
      loanTypes: ["HL", "PL"],
      tag: "Active Partner",
      segment: "South HL",
      firstContactedAt: isoDaysAgo(19),
      lastContactedAt: isoMinutesAgo(11),
      lastReplyAt: isoMinutesAgo(7),
      totalMessages: 19,
      replyCount: 8,
      leadsReferred: 4,
      convertedCount: 2,
      commissionEarned: 82000,
      engagementLevel: "Hot",
      preferredLanguage: "English",
    },
    {
      id: "dsa-002",
      name: "Priya Agency",
      phone: "9898981212",
      city: "Bengaluru",
      source: "Field list",
      loanTypes: ["PL", "BL"],
      tag: "Replied",
      segment: "South Salaried",
      firstContactedAt: isoDaysAgo(6),
      lastContactedAt: isoMinutesAgo(20),
      lastReplyAt: isoMinutesAgo(3),
      totalMessages: 9,
      replyCount: 3,
      leadsReferred: 1,
      convertedCount: 0,
      commissionEarned: 0,
      engagementLevel: "Active",
      preferredLanguage: "English",
    },
    {
      id: "dsa-003",
      name: "Sathish Finance",
      phone: "9811002200",
      city: "Chennai",
      source: "Bulk CSV",
      loanTypes: ["BL", "LAP"],
      tag: "Contacted",
      segment: "Chennai BL",
      firstContactedAt: isoDaysAgo(5),
      lastContactedAt: isoDaysAgo(2),
      lastReplyAt: null,
      totalMessages: 4,
      replyCount: 0,
      leadsReferred: 0,
      convertedCount: 0,
      commissionEarned: 0,
      engagementLevel: "Lukewarm",
      preferredLanguage: "Tamil",
    },
    {
      id: "dsa-004",
      name: "Nandhini Loans",
      phone: "9844001100",
      city: "Madurai",
      source: "Referral",
      loanTypes: ["GL", "PL"],
      tag: "New",
      segment: "Tamil Nadu Gold",
      firstContactedAt: null,
      lastContactedAt: null,
      lastReplyAt: null,
      totalMessages: 0,
      replyCount: 0,
      leadsReferred: 0,
      convertedCount: 0,
      commissionEarned: 0,
      engagementLevel: "Cold",
      preferredLanguage: "Tamil",
    },
    {
      id: "dsa-005",
      name: "Irfan Connect",
      phone: "9700097000",
      city: "Hyderabad",
      source: "Telegram bot",
      loanTypes: ["PL", "BL"],
      tag: "Contacted",
      segment: "Telugu Growth",
      firstContactedAt: isoDaysAgo(13),
      lastContactedAt: isoDaysAgo(1),
      lastReplyAt: null,
      totalMessages: 5,
      replyCount: 0,
      leadsReferred: 0,
      convertedCount: 0,
      commissionEarned: 0,
      engagementLevel: "Cold",
      preferredLanguage: "Telugu",
    },
    {
      id: "dsa-006",
      name: "Aman DSA Desk",
      phone: "9819901110",
      city: "Mumbai",
      source: "Manual",
      loanTypes: ["PL", "HL"],
      tag: "Dead",
      segment: "West Retail",
      firstContactedAt: isoDaysAgo(90),
      lastContactedAt: isoDaysAgo(30),
      lastReplyAt: isoDaysAgo(84),
      totalMessages: 12,
      replyCount: 1,
      leadsReferred: 0,
      convertedCount: 0,
      commissionEarned: 0,
      engagementLevel: "Dead",
      preferredLanguage: "Hindi",
    },
  ],
  campaigns: [
    {
      id: "camp-001",
      name: "Chennai New DSA Sprint",
      segment: "Chennai",
      status: "Running",
      template: "Same-day PL/BL intro",
      dailyLimit: 50,
      sendWindow: "09:00 - 20:00",
      randomDelayRange: "30s - 5m",
      startedAt: isoHoursAgo(6),
      senderPool: 2,
      todaySent: 18,
    },
    {
      id: "camp-002",
      name: "Silent DSAs Re-Activation",
      segment: "No reply > 7 days",
      status: "Queued",
      template: "Value-add commission proof",
      dailyLimit: 35,
      sendWindow: "10:00 - 18:00",
      randomDelayRange: "45s - 4m",
      startedAt: isoHoursAgo(1),
      senderPool: 1,
      todaySent: 0,
    },
  ],
  leads: [
    {
      id: "lead-001",
      name: "Ramesh",
      phone: "9000011111",
      city: "Chennai",
      loanType: "Personal Loan",
      amount: 500000,
      employmentType: "Salaried",
      employer: "TCS",
      sourceDsaId: "dsa-001",
      stage: "Under Review",
      createdAt: isoDaysAgo(2),
      nextAction: "Income review pending",
      daysInStage: 2,
      missingDocuments: [],
      statusNote: "DSA sent full docs overnight",
    },
    {
      id: "lead-002",
      name: "Priya",
      phone: "9000022222",
      city: "Bengaluru",
      loanType: "Personal Loan",
      amount: 300000,
      employmentType: "Salaried",
      employer: "Infosys",
      sourceDsaId: "dsa-002",
      stage: "Documents Pending",
      createdAt: isoDaysAgo(1),
      nextAction: "Need bank statement and PAN",
      daysInStage: 1,
      missingDocuments: ["PAN", "Bank statement"],
      statusNote: "Hot lead from overnight reply",
    },
    {
      id: "lead-003",
      name: "Maheshwari Traders",
      phone: "9000033333",
      city: "Madurai",
      loanType: "Business Loan",
      amount: 1800000,
      employmentType: "Self-employed",
      employer: "Maheshwari Traders",
      sourceDsaId: "dsa-001",
      stage: "Approved",
      createdAt: isoDaysAgo(8),
      nextAction: "Disbursement confirmation",
      daysInStage: 1,
      missingDocuments: [],
      statusNote: "Commission payable on disbursement",
    },
    {
      id: "lead-004",
      name: "Deepa",
      phone: "9000044444",
      city: "Hyderabad",
      loanType: "Home Loan",
      amount: 2500000,
      employmentType: "Salaried",
      employer: "Wipro",
      sourceDsaId: "dsa-005",
      stage: "New Inquiry",
      createdAt: isoMinutesAgo(26),
      nextAction: "Initial qualification call",
      daysInStage: 0,
      missingDocuments: ["Phone verification"],
      statusNote: "Fresh DSA lead needs instant callback",
    },
  ],
  borrowers: [
    {
      id: "bor-001",
      name: "Mohan",
      phone: "9444411111",
      city: "Chennai",
      loanAmount: 240000,
      emi: 12000,
      outstanding: 36000,
      daysPastDue: 22,
      dueDate: "22/03/2026",
      paymentHistory: ["paid", "paid", "missed", "missed", "partial"],
      assignedMediatorId: "med-001",
      tag: "Avoiding",
      ptp: { amount: 5000, promisedDate: isoDaysFromNow(2), fulfilled: false },
    },
    {
      id: "bor-002",
      name: "Lakshmi",
      phone: "9444422222",
      city: "Coimbatore",
      loanAmount: 160000,
      emi: 8500,
      outstanding: 17000,
      daysPastDue: 15,
      dueDate: "19/03/2026",
      paymentHistory: ["paid", "paid", "missed", "missed", "missed"],
      assignedMediatorId: "med-002",
      tag: "Willing-but-Unable",
      ptp: { amount: 8500, promisedDate: isoDaysFromNow(1), fulfilled: false },
    },
    {
      id: "bor-003",
      name: "Sanjay",
      phone: "9444433333",
      city: "Bengaluru",
      loanAmount: 420000,
      emi: 18500,
      outstanding: 18500,
      daysPastDue: 4,
      dueDate: "15/03/2026",
      paymentHistory: ["paid", "paid", "paid", "missed", "pending"],
      assignedMediatorId: "med-003",
      tag: "Cooperative",
      ptp: null,
    },
    {
      id: "bor-004",
      name: "Rekha",
      phone: "9444444444",
      city: "Hyderabad",
      loanAmount: 310000,
      emi: 13200,
      outstanding: 52800,
      daysPastDue: 94,
      dueDate: "07/12/2025",
      paymentHistory: ["missed", "missed", "missed", "missed", "missed"],
      assignedMediatorId: "med-001",
      tag: "Untraceable",
      ptp: null,
    },
  ],
  mediators: [
    {
      id: "med-001",
      name: "Suresh",
      phone: "9090901010",
      type: "Collection Agent",
      area: "North Chennai",
      status: "Active",
      commissionRule: "3% on recovered amount",
      onboardingDate: isoDaysAgo(210),
      agreementStatus: "Signed",
      tasksAssigned: 6,
      tasksCompleted: 4,
      recoveryAmount: 58000,
      documentsCollected: 1,
      avgResponseMinutes: 9,
      ptpWon: 4,
      ptpFulfilled: 1,
      commissionEarned: 1740,
      lastReportedAt: isoDaysAgo(3),
    },
    {
      id: "med-002",
      name: "Kumari",
      phone: "9090902020",
      type: "Field Mediator",
      area: "Coimbatore",
      status: "Active",
      commissionRule: "2% on recovered amount",
      onboardingDate: isoDaysAgo(130),
      agreementStatus: "Signed",
      tasksAssigned: 4,
      tasksCompleted: 4,
      recoveryAmount: 34000,
      documentsCollected: 2,
      avgResponseMinutes: 6,
      ptpWon: 3,
      ptpFulfilled: 2,
      commissionEarned: 680,
      lastReportedAt: isoHoursAgo(5),
    },
    {
      id: "med-003",
      name: "Rajesh",
      phone: "9090903030",
      type: "DSA",
      area: "Bengaluru",
      status: "Active",
      commissionRule: "1.2% on disbursed amount",
      onboardingDate: isoDaysAgo(320),
      agreementStatus: "Signed",
      tasksAssigned: 3,
      tasksCompleted: 2,
      recoveryAmount: 12000,
      documentsCollected: 5,
      avgResponseMinutes: 4,
      ptpWon: 1,
      ptpFulfilled: 1,
      commissionEarned: 45600,
      lastReportedAt: isoHoursAgo(2),
    },
  ],
  mediatorTasks: [
    { id: "task-001", mediatorId: "med-001", title: "Visit Mohan", type: "Collection", priority: "High", dueAt: isoDaysFromNow(0), status: "In Progress", notes: "Borrower overdue 22 days. Seek part payment." },
    { id: "task-002", mediatorId: "med-002", title: "Visit Lakshmi", type: "Collection", priority: "High", dueAt: isoDaysFromNow(0), status: "Assigned", notes: "PTP follow-up for ₹8,500." },
    { id: "task-003", mediatorId: "med-003", title: "Collect docs for Priya", type: "Lead Docs", priority: "Medium", dueAt: isoDaysFromNow(0), status: "Assigned", notes: "Aadhaar + salary slip pending." },
    { id: "task-004", mediatorId: "med-001", title: "Escalate Rekha", type: "NPA", priority: "Critical", dueAt: isoDaysFromNow(0), status: "Assigned", notes: "90+ DPD. Draft legal notice." },
  ],
  conversations: [
    {
      id: "conv-001",
      contactType: "DSA",
      contactId: "dsa-001",
      contactName: "Rajesh Kumar",
      channel: "WhatsApp",
      priority: "Hot",
      unreadCount: 0,
      lastMessageAt: isoMinutesAgo(5),
      messages: [
        { id: "msg-001", direction: "out", at: isoHoursAgo(4), text: "Hi Rajesh, any new loan files this week?", intent: "nurture", handledBy: "agent" },
        { id: "msg-002", direction: "in", at: isoMinutesAgo(7), text: "I have a home loan case 25L in Chennai. Salaried couple.", intent: "new_case", handledBy: "contact" },
        { id: "msg-003", direction: "out", at: isoMinutesAgo(5), text: "Great. Please share borrower name, contact number, salary range and property city. I will check fit immediately.", intent: "qualification", handledBy: "agent" },
      ],
    },
    {
      id: "conv-002",
      contactType: "Lead",
      contactId: "lead-002",
      contactName: "Priya",
      channel: "WhatsApp",
      priority: "Warm",
      unreadCount: 1,
      lastMessageAt: isoMinutesAgo(1),
      messages: [
        { id: "msg-004", direction: "out", at: isoHoursAgo(3), text: "Hi Priya, please share PAN and latest bank statement to proceed.", intent: "doc_request", handledBy: "agent" },
        { id: "msg-005", direction: "in", at: isoMinutesAgo(1), text: "Can I send the bank statement tonight? PAN I can share now.", intent: "doc_query", handledBy: "contact", pending: true },
      ],
    },
    {
      id: "conv-003",
      contactType: "Borrower",
      contactId: "bor-001",
      contactName: "Mohan",
      channel: "WhatsApp",
      priority: "Escalation",
      unreadCount: 0,
      lastMessageAt: isoHoursAgo(2),
      messages: [
        { id: "msg-006", direction: "out", at: isoHoursAgo(2), text: "Your account is 22 days overdue. Please clear ₹36,000 or confirm a payment date today.", intent: "collection", handledBy: "agent" },
      ],
    },
    {
      id: "conv-004",
      contactType: "Mediator",
      contactId: "med-002",
      contactName: "Kumari",
      channel: "WhatsApp",
      priority: "Operational",
      unreadCount: 0,
      lastMessageAt: isoHoursAgo(5),
      messages: [
        { id: "msg-007", direction: "in", at: isoHoursAgo(5), text: "Visited Lakshmi. She promised 8500 by tomorrow evening.", intent: "visit_update", handledBy: "contact" },
        { id: "msg-008", direction: "out", at: isoHoursAgo(5), text: "Logged. I will check tomorrow and prompt if unpaid.", intent: "ack", handledBy: "agent" },
      ],
    },
    {
      id: "conv-005",
      contactType: "DSA",
      contactId: "dsa-002",
      contactName: "Priya Agency",
      channel: "WhatsApp",
      priority: "Hot",
      unreadCount: 1,
      lastMessageAt: isoMinutesAgo(2),
      messages: [
        { id: "msg-009", direction: "in", at: isoMinutesAgo(2), text: "What commission for salaried PL?", intent: "commission_query", handledBy: "contact", pending: true },
      ],
    },
  ],
  activityFeed: [
    { id: "act-001", at: isoMinutesAgo(1), lane: "DSA Outreach", text: "DSA Priya Agency replied: 'What commission for salaried PL?' Queue picked for instant response." },
    { id: "act-002", at: isoMinutesAgo(3), lane: "Lead Pipeline", text: "Lead Priya uploaded PAN. Documents Pending checklist updated." },
    { id: "act-003", at: isoMinutesAgo(8), lane: "DSA Outreach", text: "Auto-responded to Rajesh Kumar after new HL case inquiry." },
    { id: "act-004", at: isoMinutesAgo(14), lane: "Collections", text: "Firm reminder sent to Mohan for ₹36,000 overdue." },
    { id: "act-005", at: isoHoursAgo(5), lane: "Mediators", text: "Kumari logged visit: Lakshmi promised ₹8,500 by tomorrow." },
    { id: "act-006", at: isoHoursAgo(6), lane: "DSA Outreach", text: "Campaign 'Chennai New DSA Sprint' sent 18 introductions inside safety cap." },
  ],
  scheduledReports: [
    { id: "rep-001", name: "Daily DSA Outreach Summary", cadence: "Daily 9:00 PM", destination: "WhatsApp", status: "Active" },
    { id: "rep-002", name: "Weekly Lead Pipeline Report", cadence: "Monday 8:00 AM", destination: "WhatsApp + Email", status: "Active" },
    { id: "rep-003", name: "Monthly Collection Summary", cadence: "1st of month 9:00 AM", destination: "Email PDF", status: "Active" },
  ],
  settings: {
    llmProvider: "OpenAI GPT",
    fastReplyModel: "gpt-4o-mini",
    complexReasoningModel: "Claude",
    bulkOpsModel: "DeepSeek",
    tone: "Friendly-Professional",
    languagePriority: ["English", "Hindi", "Tamil"],
    workingHours: "09:00 - 20:00",
    holidayMode: "Volume down on holidays",
    dailyMessageLimit: 50,
    minDelaySeconds: 60,
    cooldownEvery: 20,
    cooldownMinutes: 30,
    rotateNumbers: true,
    companyName: "OpenClaw Finance",
    gstin: "",
    products: [
      { code: "PL", label: "Personal Loan", amountRange: "₹50K - ₹20L", rate: "12% - 28%", commission: "1.5% - 2.5%" },
      { code: "BL", label: "Business Loan", amountRange: "₹2L - ₹50L", rate: "14% - 26%", commission: "1.75% - 3%" },
      { code: "HL", label: "Home Loan", amountRange: "₹5L - ₹2Cr", rate: "8.5% - 13%", commission: "0.75% - 1.25%" },
      { code: "GL", label: "Gold Loan", amountRange: "₹25K - ₹50L", rate: "9% - 18%", commission: "0.8% - 1.5%" },
    ],
  },
});
